### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by alexandcote** [louim/bedrock-site-protect#5]
As-tu une idée comment nous pourrions implémenter le support de plusieurs users ?

Je suggère d'utilisé un array de user dans le fichier de configuration comme ceci:

```
htpasswd:
      - name: firstUser
        password: firstPassword
      - name: secondUser
        password: secondPassword
```

Par contre, lorsque j'essaye de l'implémenter dans ton role, je n'y parvient pas.

```
- name: Set htpasswd
  htpasswd:
    path: "{{ htpasswd_path }}/{{ item.0.key }}"
    name: "{{ item.1.name }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt|default(omit) }}"
    owner: root
    group: root
    mode: 0644
  with_subelements:
    - wordpress_sites
    - htpasswd
    - skip_missing: yes
```

En gros, `item.0.key` n'existe pas. Je ne sais pas si tu as une autre solution ? 

Thanks.
